### ISSUE TITLE
Server error with issues 

### ISSUE THREAD

**Issue by hschachn** [nanego/redmine_customize_core_fields#4]
Hello,

after installing the plugin, I get server errors when trying to edit or create issues.
I am using the following configuration:

    Environment:
      Redmine version                3.2.0.stable.15148
      Ruby version                   2.1.2-p95 (2014-05-08) [i686-linux]
      Rails version                  4.2.5.1
      Environment                    production
      Database adapter               Mysql2
    SCM:
      Subversion                     1.6.17
      Git                            1.7.10.4
      Filesystem                     
    Redmine plugins:
      computed_custom_field          0.0.6
      redmine_base_deface            0.0.1
      redmine_my_page                0.1.9
      redmine_tweaks                 0.5.9-dev

As recommended, I issued the following commands after having cloned the plugin code into the plugins-folder

    bundle install
    rake redmine:plugins:migrate RAILS_ENV=production

Additional info: `bundle install` complains about duplicate gem `deface`. 

    Your Gemfile lists the gem deface (>= 0) more than once.
    You should probably keep only one of them.

Does the plugin depend on a specific version of `deface`? With the plugin installed,
deface 1.0.2 is used, otherwise 1.1.0.

When trying to edit a specific issue, the server crashes, creating the following
log output:

    Started GET "/issues/1513" for 172.25.3.21 at 2016-12-20 14:10:45 +0100
    Processing by IssuesController#show as HTML
      Parameters: {"id"=>"1513"}
      Current user: admin (id=1)
      Rendered issues/_action_menu.html.erb (8.5ms)
      Rendered issues/show.html.erb within layouts/base (42.4ms)
    Completed 500 Internal Server Error in 256ms (ActiveRecord: 17.6ms)

    ActionView::Template::Error (undefined local variable or method `acts_as_positioned' for #<Class:0xec2a228>):
        38:   rows.left l(:field_status), @issue.status.name, :class => 'status'
        39:   rows.left l(:field_priority), @issue.priority.name, :class => 'priority'
        40:
        41:   unless @issue.disabled_core_fields.include?('assigned_to_id')
        42:     rows.left l(:field_assigned_to), avatar(@issue.assigned_to, :size => "14").to_s.html_safe + (@issue.assig
    ned_to ? link_to_user(@issue.assigned_to) : "-"), :class => 'assigned-to'
        43:   end
        44:   unless @issue.disabled_core_fields.include?('category_id') || (@issue.category.nil? && @issue.project.issue
    _categories.none?)
      plugins/redmine_customize_core_fields/app/models/core_field.rb:5:in `<class:CoreField>'
      plugins/redmine_customize_core_fields/app/models/core_field.rb:1:in `<top (required)>'
      plugins/redmine_customize_core_fields/lib/redmine_customize_core_fields/issue_patch.rb:7:in `disabled_core_fields'
      app/views/issues/show.html.erb:41:in `block in _eda23c3090300f203155473bffc28add'
      app/helpers/issues_helper.rb:209:in `issue_fields_rows'
      app/views/issues/show.html.erb:37:in `_eda23c3090300f203155473bffc28add'
      app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
      app/controllers/issues_controller.rb:115:in `show'
      lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by hschachn** [comment]
Remark: As mentioned in the Readme, the plugin should work with 3.2+. Which version was actually used for testing? Maybe I have a different version installed.

**Comment by nanego** [comment]
Hi
You are right, the last version of this plugin is only compatible with Redmine 3.3.
You may either upgrade your Redmine application or use a previous version of the plugin.

**Comment by hschachn** [comment]
Thank you for your answer, I'll try to use a previous version.
