### ISSUE TITLE
Does not work with Redmine 3.3.1

### ISSUE THREAD

**Issue by slabstone** [nanego/redmine_customize_core_fields#9]
I'm getting this message after `bundle exec rake redmine:plugins:migrate`:
`NoMethodError: undefined method '[]' for #<ActiveRecord::Migration:0x0000000350c3e8>`

**Comment by nanego** [comment]
Yes, the plugin has been updated for Redmine 4. With Redmine 3, you will have to use an older version. Try this commit: df2442a78913b624796b747b0647797645376f87

**Comment by slabstone** [comment]
df2442a seems to work, can you please update the `README.md`?

**Comment by maxxer** [comment]
@nanego you can create a tag for 3.3 at that rev
